### PR TITLE
IDbAsyncEnumerable implementation for DbContext Async operations

### PR DESCRIPTION
**Pull request by lucasteles**

### CODE REVIEW

**Comment by mgibas** [comment]
Thanks a lot for a PR!
I have just couple minor issues that u can easily fix and we can merge it:
- Move new classes into separate files
- Name new classes without "Test" - maybe something like `FakeDbAsyncQueryProvider` instead of `TestDbAsyncQueryProvider`
- Do not use regions and comments (that should be taken care of after moving to separate files)
- Write some simple test that will cover your changes

I know these conventions are not described in readme - sorry for that :(

**Comment by lucasteles** [comment]
Hy 

Ok, i will do  this changes as soon as possible.

Sorry about it

**Comment by lucasteles** [comment]
Done

**Review by mgibas — APPROVED** [review]
Looks great, thanks a lot

**Comment by mgibas** [comment]
Published: `EntityFramework.Testing.FakeItEasy.1.0.16.0.nupkg`

**Pull request merged**
