### PR TITLE
AsNoTracking (and readme) update

### PR DESCRIPTION
**Pull request by thinkOfaNumber**
Hi Maciej, big thanks for this project as it helped me get over the same problem. I've added AsNoTracking so that those queries work too, and touched the readme (just a suggestion). What do you think?

### CODE REVIEW

**Comment by thinkOfaNumber** [comment]
hm, it looks like there's a build/test failure that I don't get locally - let me look into that!

**Comment by mgibas** [comment]
`AsNoTracking` seems to be extension method ? In this case we would need to mock whatever is used underneath :(

**Comment by mgibas** [comment]
Fixed and added small unit test to verify - let me know if u have any issues with this.

**Comment by thinkOfaNumber** [comment]
Sorry I couldn't get back sooner - that looks good, thanks! There must be a EF or Fakeiteasy version difference that is causing the slight different behaviour.

**Pull request merged**
